# Generated by Django 2.0.6 on 2021-08-25 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarFood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(default='n/a', max_length=80)),
                ('Apellido', models.TextField(default='n/a', max_length=80)),
                ('Tarjeta', models.IntegerField()),
                ('Identificacion', models.IntegerField()),
                ('Ncontacto', models.IntegerField(max_length=8)),
                ('Ubicacion', models.TextField(default='n/a', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('pk_Nfactura', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nfactura', models.IntegerField(max_length=12)),
                ('total_a_pagar', models.IntegerField()),
                ('fk_Productos', models.TextField(default='n/a', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('pk_Nmesa', models.AutoField(primary_key=True, serialize=False)),
                ('reservacion', models.BooleanField()),
                ('Cantidad_Sillas', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(default='n/a', max_length=80)),
                ('Apellido', models.TextField(default='n/a', max_length=80)),
                ('DPI', models.IntegerField()),
                ('Puesto', models.TextField(default='n/a', max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='name',
        ),
        migrations.AddField(
            model_name='factura',
            name='fk_Menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarFood.Menu'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fk_Mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarFood.Mesa'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fk_Trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarFood.Trabajador'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fk_clientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarFood.Cliente'),
        ),
    ]
